FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    gawk \
    wget \
    git \
    diffstat \
    unzip \
    texinfo \
    gcc \
    build-essential \
    chrpath \
    socat \
    cpio \
    python3 \
    python3-pip \
    python3-pexpect \
    xz-utils \
    debianutils \
    iputils-ping \
    python3-git \
    python3-jinja2 \
    python3-subunit \
    zstd \
    liblz4-tool \
    file locales \
    libacl1 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN locale-gen en_US.UTF-8 && update-locale LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8

RUN pip install --no-cache-dir kas

ARG USER_ID=1000
ARG GROUP_ID=1000

ENV USER_NAME avocado
ENV DL_DIR /avocado/dl
ENV DL_DIR /avocado/sstate
ENV BB_ENV_PASSTHROUGH_ADDITIONS "DL_DIR SSTATE_DIR"

RUN groupadd -g $GROUP_ID $USER_NAME && \
    useradd -g $GROUP_ID -m -s /bin/bash -u $USER_ID $USER_NAME

RUN mkdir -p /avocado/build /avocado/sstate /avocado/dl && chown -R avocado:avocado /avocado
RUN echo "root  ALL = NOPASSWD: /bin/su ALL" >> /etc/sudoers

USER avocado
WORKDIR /avocado-build
