header:
  version: 11
  includes:
    - meta-avocado-example/conf/kas/peridio.yml

build_system: oe

repos:
  bitbake:
    url: https://git.openembedded.org/bitbake
    commit: 8714a02e13477a9d97858b3642e05f28247454b5
    branch: '2.8'
    layers:
      .: excluded

  meta-avocado:
    path: meta-avocado/meta-avocado

  meta-avocado-example:
    path: meta-avocado/meta-avocado-example

  meta-openembedded:
    url: https://git.openembedded.org/meta-openembedded
    commit: 18f939a5fb37528a5415b05077ece383c346a119
    branch: scarthgap
    layers:
      meta-oe:
      meta-perl:
      meta-python:
      meta-networking:
      meta-filesystems:
      meta-multimedia:

  openembedded-core:
    url: https://git.openembedded.org/openembedded-core
    commit: 6cd503c5e84bf8090b840c69c7569ae1a46528d0
    branch: scarthgap
    layers:
      meta:

  meta-virtualization:
    url: https://git.yoctoproject.org/meta-virtualization
    commit: 6a80f140e387621f62964209a2e07d3bcfb125ce
    branch: scarthgap
    layers:
      .:

distro: avocado

env:
    TEMPLATECONF: ../meta-avocado/conf/templates/default

local_conf_header:
  meta-avocado: |
    USER_CLASSES:append = " buildhistory buildstats buildstats-summary"
    EXTRA_IMAGE_FEATURES ?= "debug-tweaks"
    PACKAGECONFIG:append:pn-gnutls = " p11-kit"

  sdk: |
    CONF_VERSION = "2"

target:
 - avocado-image-base
